# using code from 
# - https://www.youtube.com/watch?v=RcxvrhQKv8I
# - https://marketplace.visualstudio.com/items?itemName=humao.rest-client
@host = http://127.0.0.1:5000
@access = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2NDcxMDE4NCwianRpIjoiYzdkNGY1ZWEtZGViYS00NjlmLWEwZGEtNzg5MGQ5MTMzNTkyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Im1ib3dlciIsIm5iZiI6MTc2NDcxMDE4NCwiY3NyZiI6IjY4ODQxNjUzLTUzYzgtNDJhYi1hNTM4LTRkY2M1ZjE1ZTU2MSIsImV4cCI6MTc2NDcxMTA4NH0.YQKspjlZI4kbocFZ1KyXLqYLduxLxY2nUl-Yo2b2bdE
@refresh = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MzA1MjgzMSwianRpIjoiOTZhZjcxZGEtNjI1NC00YjE0LWIzN2QtMDY0Zjc1ZDg2ODU3IiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiJtYm93ZXIiLCJuYmYiOjE3NjMwNTI4MzEsImNzcmYiOiIyMTYzY2ZkZS02NWY4LTQzYzEtOWZmNy0xMDcyZmI3MjkyYzMiLCJleHAiOjE3NjU2NDQ4MzF9.ntU8u1eQkY8usFqIoe2Nf9wJNekn1uwgTTdq2VqIiZQ

### ROOT ###

get {{host}}

### USER ###
# sign up user
post {{host}}/user/sign-up
Content-Type: application/json

{
    "email": "mitchell@bowermail.com",
    "password": "d3mon$tration",
    "username": "mbower"
}

# Use this to make admin at first:
#    update "user" set clearance = 'admin' where id = 1;

###
# log in user
post {{host}}/user/log-in
Content-Type: application/json

{
    "password": "d3mon$tration",
    "username": "mbower"
}

###
# refresh user
get {{host}}/user/refresh
Authorization: Bearer {{refresh}}

###
# log out token
get {{host}}/user/log-out
Authorization: Bearer {{refresh}}

###
# get all users
get {{host}}/users?order-by=username&direction=desc
Authorization: Bearer {{access}}

###
# get user by id
get {{host}}/user/1
Authorization: Bearer {{access}}

###
# clearance to admin
patch {{host}}/user/clearance/2
Authorization: Bearer {{access}}

###
# clearance to user
patch {{host}}/user/clearance/7?to-user=1
Authorization: Bearer {{access}}

### PRODUCT ###
# get all
get {{host}}/products?direction=desc
Authorization: Bearer {{access}}
###
# get get types
get {{host}}/product/types
Authorization: Bearer {{access}}

###
# get by ID
get {{host}}/product/1
Authorization: Bearer {{access}}

###

post {{host}}/product
Authorization: Bearer {{access}}
Content-Type: application/json

{
    "name": "Dragon Head",
    "stock": 5,
    "price": 4.99,
    "description": "A green dragon plushie tail.",
    "image_url": "https://picsum.photos/200/300",
    "type": "head"
}

###
# update a product
patch {{host}}/product/5
Authorization: Bearer {{access}}
Content-Type: application/json

{
    "stock": 9999
}

###
# delete a product
delete {{host}}/product/12
Authorization: Bearer {{access}}

### ORDER ###
# get ALL orders
get {{host}}/orders
Authorization: Bearer {{access}}

###
# get orders by a user
get {{host}}/orders/user/1?direction=desc&filter=fulfilled
Authorization: Bearer {{access}}

###
# get orders for current user
get {{host}}/orders/my?order-by=fulfilled&direction=desc&filter=unfulfilled
Authorization: Bearer {{access}}

###
# get order by ID
get {{host}}/order/4
Authorization: Bearer {{access}}

###
# post new order
post {{host}}/order
Authorization: Bearer {{access}}
Content-Type: application/json

{
    "ordered_products": [
        {
            "id": 1,
            "quantity": 2
        },
        {
            "id": 2,
            "quantity": 1
        },
    ]
}

###
# fulfill an order
patch {{host}}/order/fulfill/1
Authorization: Bearer {{access}}

###
# unfulfill an order
patch {{host}}/order/fulfill/8?to-null=1
Authorization: Bearer {{access}}

###
# delete an order
delete {{host}}/order/1
Authorization: Bearer {{access}}