# using code from https://www.youtube.com/watch?v=RcxvrhQKv8I
@host = http://127.0.0.1:5000

### ROOT ###

get {{host}}

### USER ###

get {{host}}/users

###

get {{host}}/user/2

###
# clearance to admin
patch {{host}}/user/clearance/2

###
# clearance to user
patch {{host}}/user/clearance/2?to-user=1

### PRODUCT ###
# get all
get {{host}}/products

###
# get get types
get {{host}}/product/types

###
# get by ID
get {{host}}/product/5

###

post {{host}}/product
Content-Type: application/json

{
    "name": "Dragon Tail2",
    "stock": 5,
    "description": "A green dragon plushie tail.",
    "type": "tail"
}

###
# update a product
patch {{host}}/product/12
Content-Type: application/json

{
    "stock": 60
}

###
# delete a product
delete {{host}}/product/12

### ORDER ###
# get ALL orders
get {{host}}/orders

###
# get orders from a user
get {{host}}/orders/user/1

###
# get order by ID
get {{host}}/order/8

###
# post new order
post {{host}}/order
Content-Type: application/json

{
    "user_id": 1,
    "ordered_products": [
        {
            "id": 900,
            "quantity": 1
        }
    ]
}

###
# fulfill an order
patch {{host}}/order/fulfill/7

###
# unfulfill an order
patch {{host}}/order/fulfill/8?to-null=1

###
# delete an order
delete {{host}}/order/8