# using code from 
# - https://www.youtube.com/watch?v=RcxvrhQKv8I
# - https://marketplace.visualstudio.com/items?itemName=humao.rest-client
@host = http://127.0.0.1:5000

### ROOT ###

get {{host}}

### USER ###
# sign up user
post {{host}}/user/sign-up
Content-Type: application/json

{
    "email": "test@email.com",
    "password": "d3mon$tration",
    "username": "testtest10"
}

# Use this to make admin at first:
#    update "user" set clearance = 'admin' where id = 1;

###
# log in user
post {{host}}/user/log-in
Content-Type: application/json

{
    "password": "d3mon$tration",
    "username": "testtest"
}

###
# refresh user
get {{host}}/user/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MzM3NiwianRpIjoiZDgzMGY4ZmYtODNiMi00NDg1LWJjMjYtZTNjYjk2YjhmNDdlIiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiJ0ZXN0dGVzdDEwIiwibmJmIjoxNzYyNTQzMzc2LCJjc3JmIjoiOWZjYjEzZTItY2M5OC00YjBlLWFhMmYtN2MzMjk1MTVjNTNlIiwiZXhwIjoxNzYyNjUxMzc2fQ.5zCEMpVJQcBtnpwk_5hSuOCP4M06_BOma5nf2Kjyzc0

###
# log out token
get {{host}}/user/log-out
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg

###
# get all users
get {{host}}/users?order-by=username&direction=desc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg

###
# get user by id
get {{host}}/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg

###
# clearance to admin
patch {{host}}/user/clearance/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg

###
# clearance to user
patch {{host}}/user/clearance/7?to-user=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg

### PRODUCT ###
# get all
get {{host}}/products?direction=desc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg
###
# get get types
get {{host}}/product/types
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MzM4NywianRpIjoiNGFiOTEzYmYtYTRhNy00MTk4LTkxZWMtMWE2ZTJmYzM2ZmVmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0MTAiLCJuYmYiOjE3NjI1NDMzODcsImNzcmYiOiJjOGRhNzU0NC1lZjY5LTQ1MGEtYjE2Ni00OTczOGRiOGU2YjYiLCJleHAiOjE3NjI1NDQyODd9.IoSXGNBHofY2Cth6SGfyKrh739ay2zoR3cVhaZTc1sg

###
# get by ID
get {{host}}/product/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg

###

post {{host}}/product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg
Content-Type: application/json

{
    "name": "Dragon Tail2",
    "stock": 5,
    "price": 4.99,
    "description": "A green dragon plushie tail.",
    "image_url": "https://picsum.photos/200/300",
    "type": "tail"
}

###
# update a product
patch {{host}}/product/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg
Content-Type: application/json

{
    "stock": 9999
}

###
# delete a product
delete {{host}}/product/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg

### ORDER ###
# get ALL orders
get {{host}}/orders?direction=desc&filter=fulfilled
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg

###
# get orders by a user
get {{host}}/orders/user/1?direction=desc&filter=fulfilled
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg

###
# get orders for current user
get {{host}}/orders/my?order-by=fulfilled&direction=desc&filter=unfulfilled
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg

###
# get order by ID
get {{host}}/order/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg

###
# post new order
post {{host}}/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg
Content-Type: application/json

{
    "ordered_products": [
        {
            "id": 1,
            "quantity": 1
        }
    ]
}

###
# fulfill an order
patch {{host}}/order/fulfill/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg

###
# unfulfill an order
patch {{host}}/order/fulfill/8?to-null=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg

###
# delete an order
delete {{host}}/order/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MjU0MTI5MSwianRpIjoiNWYwMDEzMzItNWUzNS00NTIwLWJjZWItNmRhNGIxODE4Y2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3R0ZXN0IiwibmJmIjoxNzYyNTQxMjkxLCJjc3JmIjoiMGNmNzNhYWQtMmM0YS00YTRlLWIxYWItMWZkOGE3NjMxZTNhIiwiZXhwIjoxNzYyNTQyMTkxLCJjbGVhcmFuY2UiOiJhZG1pbiJ9.6LtQDAJr_peEVGYlpU5S_FrHtxcZKBYjMWmdMOnxACg